#!/usr/bin/env bash
set -e

BUSYBOX_VER=1.27.2
LIBTOOL_VER=2.4.6
GCC_VER=7.2.0
MUSL_VER=1.1.18
BINUTILS_VER=2.28.1
LINUX_VER=4.4.10
GMP_VER=6.1.2
MPFR_VER=3.1.5
MPC_VER=1.0.3
ISL_VER=0.18
MAKE_VER=4.2.1

DOWNLOADDIR=$(pwd)/downloads
mkdir -p $DOWNLOADDIR

if [[ ! -f "$DOWNLOADDIR/linux-${LINUX_VER}.tar.xz" ]] ; then
    curl -R -L -o $DOWNLOADDIR/linux-${LINUX_VER}.tar.xz "https://www.kernel.org/pub/linux/kernel/v4.x/linux-${LINUX_VER}.tar.xz"
fi

if [[ ! -f "$DOWNLOADDIR/busybox-${BUSYBOX_VER}.tar.bz2" ]] ; then
    curl -R -L -o $DOWNLOADDIR/busybox-$BUSYBOX_VER.tar.bz2 "https://busybox.net/downloads/busybox-$BUSYBOX_VER.tar.bz2"
fi

if [[ ! -f "$DOWNLOADDIR/musl-${MUSL_VER}.tar.gz" ]] ; then
    curl -R -L -o $DOWNLOADDIR/musl-${MUSL_VER}.tar.gz "https://www.musl-libc.org/releases/musl-${MUSL_VER}.tar.gz"
fi

if [[ ! -f "$DOWNLOADDIR/make-${MAKE_VER}.tar.bz2" ]] ; then
    curl -R -L -o $DOWNLOADDIR/make-${MAKE_VER}.tar.bz2 "https://ftp.gnu.org/gnu/make/make-${MAKE_VER}.tar.bz2"
fi

if [[ ! -f "$DOWNLOADDIR/binutils-${BINUTILS_VER}.tar.xz" ]] ; then
    curl -R -L -o $DOWNLOADDIR/binutils-${BINUTILS_VER}.tar.xz "https://ftp.gnu.org/gnu/binutils/binutils-${BINUTILS_VER}.tar.xz"
fi

if [[ ! -f "$DOWNLOADDIR/gcc-${GCC_VER}.tar.xz" ]] ; then
    curl -R -L -o $DOWNLOADDIR/gcc-${GCC_VER}.tar.xz "https://ftp.gnu.org/gnu/gcc/gcc-${GCC_VER}/gcc-${GCC_VER}.tar.xz"
fi

if [[ ! -f "$DOWNLOADDIR/gmp-${GMP_VER}.tar.xz" ]] ; then
    curl -R -L -o $DOWNLOADDIR/gmp-${GMP_VER}.tar.xz "https://ftp.gnu.org/gnu/gmp/gmp-${GMP_VER}.tar.xz"
fi

if [[ ! -f "$DOWNLOADDIR/mpfr-${MPFR_VER}.tar.xz" ]] ; then
    curl -R -L -o $DOWNLOADDIR/mpfr-${MPFR_VER}.tar.xz "https://ftp.gnu.org/gnu/mpfr/mpfr-${MPFR_VER}.tar.xz"
fi

if [[ ! -f "$DOWNLOADDIR/mpc-${MPC_VER}.tar.gz" ]] ; then
    curl -R -L -o $DOWNLOADDIR/mpc-${MPC_VER}.tar.gz "https://ftp.gnu.org/gnu/mpc/mpc-${MPC_VER}.tar.gz"
fi

if [[ ! -f "$DOWNLOADDIR/isl-${ISL_VER}.tar.xz" ]] ; then
    curl -R -L -o $DOWNLOADDIR/isl-${ISL_VER}.tar.xz "http://isl.gforge.inria.fr/isl-${ISL_VER}.tar.xz"
fi

if [[ ! -f "$DOWNLOADDIR/libtool-${LIBTOOL_VER}.tar.xz" ]] ; then
    curl -R -L -o "$DOWNLOADDIR/libtool-${LIBTOOL_VER}.tar.xz" \
      "https://ftp.gnu.org/gnu/libtool/libtool-${LIBTOOL_VER}.tar.xz"
fi

if [[ ! -f "$DOWNLOADDIR/travis_wait_log" ]] ; then
    curl -R -L -o "$DOWNLOADDIR/travis_wait_log" \
      "https://raw.githubusercontent.com/slodki/travis-wait-log/master/travis_wait_log"
    chmod +x $DOWNLOADDIR/travis_wait_log
fi
