#!/bin/sh
set -e

if [ -z "${TRAVIS_TAG}" ] ; then exit 0 ; fi
USERNAME=$(echo ${TRAVIS_REPO_SLUG} | cut -d"/" -f1)
REPONAME=$(echo ${TRAVIS_REPO_SLUG} | cut -d"/" -f2)

export PATH="$(pwd)/downloads/bin:$PATH"

github-release \
  release \
  --user "${USERNAME}" \
  --repo "${REPONAME}" \
  --tag "${TRAVIS_TAG}" || true

for f in dist/chroot*.tar.gz ; do
    github-release \
      upload \
      --user "${USERNAME}" \
      --repo "${REPONAME}" \
      --tag "${TRAVIS_TAG}" \
      --name "$(basename $f)" \
      --file "$f"
done

